## 빅데이터 주요모듈 학습

###  Numpy

In [9]:
# numpy 설치
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

np.__version__

'1.26.4'

In [11]:
lst = [1,2,3,4,5]
vec = np.array(lst)
vec

array([1, 2, 3, 4, 5])

In [12]:
vec = np.array([1,3,5,7,9])
vec

array([1, 3, 5, 7, 9])

In [13]:
# 현재 vec의 형태 확인
# 1차원 배열 - (크기, )
vec.shape

(5,)

In [14]:
# 파이썬에서 2차원 리스트는 가변이 가능
lst2 = [[1,2,3],[4,5,6,7]]
lst2

[[1, 2, 3], [4, 5, 6, 7]]

In [15]:
# 2차원 배열 
mat = np.array([[1,2,3], [4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# 2차원 배열 - (행, 열)
mat.shape

(2, 3)

In [18]:
print(type(lst), type(vec))
print(type(lst2), type(mat))

<class 'list'> <class 'numpy.ndarray'>
<class 'list'> <class 'numpy.ndarray'>


In [19]:
# 배열 초기화
mat_one = np.ones((2,3))
mat_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
mat_zero = np.zeros((2,3))
mat_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 단위행렬
mat_unit = np.eye(3)
mat_unit

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# 랜덤행렬
mat_rand = np.random.random(3)
mat_rand

array([0.6449521 , 0.85463794, 0.32833176])

In [24]:
# 0~9까지 초기화 배열
vec_rng = np.arange(10)
vec_rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 행렬 연산에 +, -, *, / 연산 가능
- np.add(), np.substract(), np.muliply(), np.divide()로도 사용가능

### Pandas

- 손쉬운 데이터처리를 위한 라이브러리. 데이터분석 시 필수 라이브러리

#### 설치

```shell
> pip install pandas
```

In [25]:
# Pandas 설치
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
import pandas as pd

pd.__version__

'2.2.3'

In [ ]:
#### 데이터 구조
- DataFrame : 2차원 배열과 동일(기본타입)
- Series : 1차원 배열과 동일(단위타입)